<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Plant extends \AppBundle\Entity\Plant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'area', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'seed', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'seedlingDate', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'seedlingAmount', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'areaCapacity', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'harvestingDate', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'disposingDate', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'note', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'action', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'createdAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'area', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'seed', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'seedlingDate', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'seedlingAmount', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'areaCapacity', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'harvestingDate', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'disposingDate', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'note', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'action', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\Plant' . "\0" . 'createdAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Plant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setSeedlingDate($seedlingDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeedlingDate', [$seedlingDate]);

        return parent::setSeedlingDate($seedlingDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeedlingDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeedlingDate', []);

        return parent::getSeedlingDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeedlingAmount($seedlingAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeedlingAmount', [$seedlingAmount]);

        return parent::setSeedlingAmount($seedlingAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeedlingAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeedlingAmount', []);

        return parent::getSeedlingAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setArea(\AppBundle\Entity\Area $area = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArea', [$area]);

        return parent::setArea($area);
    }

    /**
     * {@inheritDoc}
     */
    public function getArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArea', []);

        return parent::getArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeed(\AppBundle\Entity\Seed $seed = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeed', [$seed]);

        return parent::setSeed($seed);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeed', []);

        return parent::getSeed();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreaCapacity($areaCapacity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreaCapacity', [$areaCapacity]);

        return parent::setAreaCapacity($areaCapacity);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreaCapacity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreaCapacity', []);

        return parent::getAreaCapacity();
    }

    /**
     * {@inheritDoc}
     */
    public function setHarvestingDate($harvestingDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHarvestingDate', [$harvestingDate]);

        return parent::setHarvestingDate($harvestingDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getHarvestingDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHarvestingDate', []);

        return parent::getHarvestingDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisposingDate($disposingDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisposingDate', [$disposingDate]);

        return parent::setDisposingDate($disposingDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisposingDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisposingDate', []);

        return parent::getDisposingDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setAction($action)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAction', [$action]);

        return parent::setAction($action);
    }

    /**
     * {@inheritDoc}
     */
    public function getAction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAction', []);

        return parent::getAction();
    }

}
